# Generated by Django 3.2.11 on 2022-03-29 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wm', '0002_commonsubject'),
        ('accounts2', '0009_profile_common_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='common_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wm.commonsubject'),
        ),
    ]
